# Generated by Django 3.1.12 on 2021-08-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='staff',
        ),
    ]
