# Generated by Django 3.1.12 on 2021-08-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
