# Generated by Django 3.1.12 on 2021-08-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210810_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
